### PR TITLE
Fix Event Bugs

### LINKED ISSUE #149: Bug Fixes for Event
Bugs:

- [x] Blank Spaces for Event Name should not be accepted (i.e., `adde 1 n/           d/ 19-09-2000`)
- [x] End Time should be >= Start Time
- [x] Have a specific error message for invalid prefix commands

Documentation:
- [x] No support for multiple day events
- [x] Java Header Docs

### PR DESCRIPTION
**Pull request by SherisseTJW**
Bugs:

- [x] Blank Spaces for Event Name should not be accepted (i.e., `adde 1 n/           d/ 19-09-2000`)
- [x] End Time should be >= Start Time
- [x] Have a specific error message for invalid prefix commands

Documentation:
- [x] No support for multiple day events
- [x] Java Header Docs

Fixes #149

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java [hunk 1]
```diff
@@ -142,8 +145,8 @@ private static String extractArgumentValue(String argsString,
     }
 
     /**
-     * Checks for invalid prefixes other than {@code \t} in the provided arguments string.
-     * Throws a ParseException if any prefix other than {@code \t} is found.
+     * Checks for invalid prefixes other than {@code t/} in the provided arguments string.
+     * Throws a ParseException if any prefix other than {@code t/} is found.
```
Comment (NeoHW) [inline src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java:149]: good catch

File: src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java [hunk 2]
```diff
@@ -154,7 +157,27 @@ public static void checkInvalidPrefixesForTags(String argsString) throws ParseEx
...
+     * @throws ParseException If an invalid prefix is found
+     */
+    public static void checkInvalidPrefixesForAddEvent(String argsString) throws ParseException {
+        List<PrefixPosition> positions = findAllPrefixPositions(argsString);
+        List<Prefix> validPrefixes = List.of(PREFIX_NAME, PREFIX_DATETIME);
+
+        for (PrefixPosition position : positions) {
+            Prefix prefix = position.getPrefix();
+            if (!validPrefixes.contains(prefix)) {
+                throw new ParseException(String.format(INVALID_PREFIXES_MESSAGE, validPrefixes));
```
Comment (NeoHW) [inline src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java:180]: Was wondering if this method could be extracted out for general use in the future to avoid code duplication, but since it's just 2 methods now, should be okay

File: src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java [hunk 3]
```diff
@@ -154,7 +157,27 @@ public static void checkInvalidPrefixesForTags(String argsString) throws ParseEx
...
+
+    /**
+     * Checks for invalid prefixes, i.e., prefixes other than {@code n/}  or {@code d/} in the provided arguments
+     * string.
+     * Throws a ParseException if any prefix other than {@code n/} or {@code d/} is found.
+     *
+     * @param argsString The arguments string to check for invalid prefixes
+     * @throws ParseException If an invalid prefix is found
+     */
+    public static void checkInvalidPrefixesForAddEvent(String argsString) throws ParseException {
```
Comment (NeoHW) [inline src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java:173]: Could this be renamed for general use of Event?

File: src/main/java/seedu/address/model/patient/Event.java [hunk 4]
```diff
@@ -12,9 +12,11 @@
...
  */
 public class Event implements Comparable<Event> {
-    public static final String MESSAGE_CONSTRAINTS =
-            "Dates should be in the format: DD-MM-YYYY, HH:mm - HH:mm, OR if there is no time period,"
-            + "in the format: DD-MM-YYYY";
+    public static final String NAME_MESSAGE_CONSTAINTS = "The Name of the Event should be alphanumerical and non-empty";
+    public static final String DATETIME_MESSAGE_CONSTRAINTS = "Dates should be in the format: DD-MM-YYYY, "
+            + "HH:mm - HH:mm, where the End Time is after the Start Time, \n"
+            + "OR if there is no time period, in the format: DD-MM-YYYY";
+    public static final String NAME_PATTERN = "^.*[^a-zA-Z0-9 ].*$";
```
Comment (NeoHW) [inline src/main/java/seedu/address/model/patient/Event.java:19]: `[^a-zA-Z0-9]` : is the not operator inside this set intended?

File: src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java (hunk 1 above)
Comment (SherisseTJW) [reply src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java:149]: :3

File: src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java (hunk 2 above)
Comment (SherisseTJW) [reply src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java:180]: mmm, @guohuang88 is planning to change for his `EditEventCommand` as well so we can look into that.

I did consider it initially, but the alternative would probably be for the Command Parser to pass in the list of valid prefixes. I am not sure if this would reduce encapsulation though

File: src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java (hunk 3 above)
Comment (SherisseTJW) [reply src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java:173]: `EditEventCommand` requires an additional prefix, `e/` so I don't think so, but can refer to the above comment as well for more info.

File: src/main/java/seedu/address/model/patient/Event.java (hunk 4 above)
Comment (SherisseTJW) [reply src/main/java/seedu/address/model/patient/Event.java:19]: oops, nice catch!

**Review by NeoHW — APPROVED** [review]
